name: Process Resume Text

on:
  repository_dispatch:
    types: [Convert PDF to Text]

permissions:
  contents: write

jobs:
  process-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required Python packages
        run: |
          pip install --upgrade pip

      - name: Run the resume processing script
        run: python process_resume.py

      - name: Commit formatted text files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add education.txt skills.txt experience.txt
          git commit -m "Split resume into education, skills, and experience"
          git push
