name: Process Resume Text

on:
  repository_dispatch:
    types: [process_resume]

permissions:
  contents: write

jobs:
  process-resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install required Python packages
        run: |
          pip install --upgrade pip
      
      - name: Check and delete existing resume section files
        id: delete_files
        run: |
          files_to_delete="education.txt experience.txt skills.txt Projects.txt"
          deleted_files=""
          for file in $files_to_delete; do
            if [ -f $file ]; then
              rm $file
              deleted_files="$deleted_files $file"
            fi
          done
          echo "deleted_files=$deleted_files" >> $GITHUB_ENV

      - name: Commit deletions if any
        if: env.deleted_files != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ env.deleted_files }}
          git commit -m "Delete existing resume section files"
          git push
          
      - name: Run the resume processing script
        run: python process_resume.py

      - name: Commit formatted text files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add education.txt skills.txt experience.txt Projects.txt
          git commit -m "Split resume into education, skills, and experience"
          git push
